name: 'Setup o3de-extras'
description: 'Custom action to setup o3de-extras'
author: 'Robotec.AI'

inputs:
  script-path:
    description: 'Path to the script with all tests defined by the user'
    required: true
    default: 'test/test-script.sh'
  o3de-extras-url:
    description: 'URL to the o3de-extras repository'
    required: false
    default: 'https://github.com/o3de/o3de-extras.git'
  branch-name:
    description: 'Branch name to checkout'
    required: false
    default: 'development'

runs:
  using: 'node16'
  main: 'dist/index.js'
